org: dotenv
app: integration-example-aws-serverless
service: integration-example-serverless-express
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    DOTENV_KEY: ${param:DOTENV_KEY}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

package:
  patterns:
    - '!.env*'
    - '.env.vault'
